### ISSUE TITLE
loading either from github or cran fails

### ISSUE THREAD

**Issue by alejandrohagan** [bayes-rules/bayesrules#92]
hi! I love the book but when I try to load the package, either directly from the site with "devtools" or from cran it fails.

Is anyone else having this issue?

**Comment by mdogucu** [comment]
What kind of error are you getting?

**Comment by alejandrohagan** [comment]
Team,

Hi
First! I love your book, thank you so much for the effort.

I am using r cloud studio for my R IDE. However I just checked and on my desktop version this packages installs fine.

Below is the error I get from the cloud studio version

***@***.***

Alejandro Hagan
CSI Cash Flow Hub

**Comment by mdogucu** [comment]
Probably because you responded to the GitHub comment via email the error you are getting is hidden.

I just went ahead and tried installing the package via CRAN on RStudio Cloud and I was able to do so. I assume it must be a one-time thing or a user-specific thing. 

I am glad you were able to install it locally at least.
